# Auth config
host: "127.0.0.1"
port: 444

# Mysql config
mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "rubis_auth"
  user: "root"
  password: ""
http:
  port: 5050
  password: "mySecretPassword"

# Debug mode
debug: false